<!DOCTYPE html>
<html>
  <head>
    <title>Enrise VPN Portal</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="navbar">
		<div class="container">
			<div class="navbar-inner">
				<a class="brand" href="http://www.enrise.com/"  style="padding:0px;margin-top:2px;padding-right:15px;padding-left:15px;" target="_blank"><img src="img/header-logo.png"/></a>
				<a class="brand" href="index.php">VPN Portal</a>
				<ul class="nav">
				  <li class="active"><a href="#">{{TITLE}}</a></li>
				</ul>
			</div>
		</div>
	</div>
	
	<div class="container">
		{{CONTENT}}
	</div>

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>